id: A8B17B73F
base_file: fF30B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:15:11.655273
  last_modified_at: 2022-06-17 14:15:11.655282
