id: A8B17B73F
base_file: f1863.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:15:11.625490
  last_modified_at: 2022-06-17 14:15:11.625515
